### ISSUE TITLE
좋아요/싫어요 요청 시 발생하는 문제

### ISSUE THREAD

**Issue by QuaRang1225** [QuaRang1225/IMad_Project#25]
> {baseurl}/api/review/2/like

```json
{
   "like_status" : 1
}
```

위의 uri와 body로 좋아요/싫어요 요청 테스트 진행 중

다음과 같은 리스폰스를 받음

```json
{
    "status": 401,
    "data": null,
    "message": "잘못된 요청이거나 올바르지 않은 인증정보입니다."
}
```

- 같은 토큰으로 리뷰 수정/삭제는 잘되는것으로 보아 인증 문제는 아닌것으로 보임

- 포스트맨에서 문제가 발생하며 iOS에서 통신테스트를 해보진 않았음(받는 response data를 모름)

- 혹시 몰라 리뷰를 새로 추가한 후 나오는 리뷰 아이디로 요청을 걸었지만 역시 위와 같은 response를 받음

**Comment by NCookies** [comment]
테스트 결과 위의 상황이 재현되지 않음. 좀 더 구체적인 설명 및 묘사가 필요함 

- 어떤 상황에서 위와 같은 문제가 발생하는지
- 로그인 계정
- 위 문제가 발생한 상태에서 리뷰 조회, 수정 등은 정상적으로 동작하는지
- request body 데이터

등...

**Comment by QuaRang1225** [comment]
## 해결

> 결론 : 포스트맨 파일들 정리하다가 갑자기 됨
### 포스트맨에서 시도한 것

- 요청파일들 저장안 되어 있는 것들 다 저장하고 창 닫음
- aws서버 요청과 local서버를 구분해서 관리함
